export const typeSymbol = Symbol('type')
export const fieldsSymbol = Symbol('fields')
export const innerTypesSymbol = Symbol('innerTypes')
export const itemMetadataSymbol = Symbol('itemMetadata')
export const innerOrigSymbol = Symbol('innerOrigSymbol')
